### ISSUE TITLE
View Demo link is broken

### ISSUE THREAD

**Issue by kefranabg** [guess-js/guess-js.github.io#6]
Hi,

View demo link is broken on this page: [https://guess-js.github.io/docs/static](https://guess-js.github.io/docs/static)

**Comment by mgechev** [comment]
@khempenius do you know if the demo is still up? Alternatively we can drop the demo link.

**Comment by kefranabg** [comment]
Btw same problem with these links:
- https://guess-js.github.io/docs/api/webpack/index
- https://guess-js.github.io/docs/api/ga/index
- https://guess-js.github.io/docs/api/parser/index

**Comment by mgechev** [comment]
Yes, we have the API docs broken for a bit. That's a known issue. If you have some time to look at it, it'll be great.

**Comment by mgechev** [comment]
Anyway, redeployment fixed the issue. I'll drop the "View demo" button.
